apiVersion: v1
kind: Service
metadata:
  name: orchestrator
spec:
  ports:
    - name: grpc
      nodePort: null
      port: 10000
      protocol: TCP
      targetPort: 10000
  selector:
    app: orchestrator
