# env <dev,sit,prod>
env: dev
is_debug: true

server:
  grpc:
    port: 10000

engine:
  # message queue <rabbit_mq, nats>
  message_queue: nats

# Message Queue
message_queue:
  topic_prefix: topic_booking_dev
  # Topics
  # - id : short name mapping ./topic/topic.go
  # - is_throttling: true: pub/sub will through same pod, default : false
  # - concurrency : count of consumers, default 1
  topics:
    - id: create_order_throttling
      is_throttling: true
      concurrency: 100
    - id: create_payment_throttling
      is_throttling: true
      concurrency: 100

client:
  nats:
    cluster_id: "test-cluster"
    client_id: orchestrator
    nats_url: "nats://nats-streaming:4222"
  burnner-grpc:
    host: burnner
    port: 10000

