version: "3"
services:
  ### Nats #############################################
  nats-streaming:
    image: nats-streaming:0.21.2-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - backend

  ## Redis ################################################
  redis:
   image: redis:latest
   ports:
     - "6379:6379"
   networks:
     - backend

  ## Burnner for test #########################################
  # each request burns 10MB, we will observe loading of container
  # orchestrator --gRPC--> burnner
  burnner:
    image: yw4code/burnner:latest
    ports:
      - "13100:10000"
    mem_limit: 100m
    networks:
      - backend
    command:
      - ./burnner

  ## HTTP Api for test #########################################
  # cli --http--> och-api --gRPC--> orchestrator
  och-api:
    image: yw4code/och-api:latest
    ports:
      - "8081:8081"
    networks:
      - backend
    environment:
      - ORC_GRPC_ADDR=host.docker.internal:10000
    command:
      - ./och-api

networks:
  backend:
    driver: "bridge"
